### ISSUE TITLE
Create Dynamic content for Navbar

### ISSUE THREAD

**Issue by jean1880** [wendelltron/tekapp#21]
#### User Story
As a user, I want the navbar to display content relevant to the page I am on, so that I can quickly interact with the app

#### Success Criteria

- [x] ~~Have content load from JSON objects, into the angular navigation template~~ *Use templates instead for more possibilities*
- [x] Create place holder content for main page and topic discussion page
- [x] Have the content area clear on page change

#### Prerequisite

- [x] Depends on checking user login #10
- [x] Depends on method to update the template #25

**Comment by DaAwesomeP** [comment]
Added to Beta release

**Comment by DaAwesomeP** [comment]
Should we simply have it load a template? This way we can add buttons too like jump to top, bottom or post number, reply, and etc. This will also give us room to add styling to lists and other elements easily (in case ever do need to add the colors for categories).

**Comment by DaAwesomeP** [comment]
Now added. Only criteria not completed is individual posts page and profile page.

**Comment by DaAwesomeP** [comment]
Finished
