### ISSUE TITLE
Add animations on events

### ISSUE THREAD

**Issue by jean1880** [wendelltron/tekapp#23]
#### User Story
As a user, I want the app to transition between views with an animation, so that the changes feel smoother, and not so rigid

#### Success Criteria
- [ ] Animation applied to each route change (see [ngAnimate](https://docs.angularjs.org/api/ngAnimate))

**Comment by jean1880** [comment]
Some nice animations can be accessed using [Animate.css](http://daneden.github.io/animate.css/)

**Comment by DaAwesomeP** [comment]
I have added [ngfx](https://github.com/Hendrixer/ngFx).
