### ISSUE TITLE
Add function to reload nav

### ISSUE THREAD

**Issue by DaAwesomeP** [wendelltron/tekapp#25]
Developer: Add function to reload nav

For instance, after login, the template needs to reload to show the profile icon/user avatar and logout button (instead of login).

---
* [ ] Add function to reload nav (right-control) template
* [x] Automatically reload every time ~~it is opened or~~ specific events occur (login, notfications bubble, etc.)

**Comment by jean1880** [comment]
I had a solution in mind for this that should take care of it, using the angular watch functionality, it can just watch the variable and if it changes, then handle updating the right control view

**Comment by jean1880** [comment]
That would reduce CPU load, keeping it from doing a task when it isn't required

**Comment by DaAwesomeP** [comment]
It just needs to update on notification and login/logout events. We need a function to do that first though. No need to mess with watching; we can just put the update function into the login and notification scripts.

**Comment by jean1880** [comment]
Ah, true enough, yes, good idea, I just didn't want to have it doing it every single time the user opened/closed the nav menu

**Comment by DaAwesomeP** [comment]
Yeah, that's probably a little excessive.

**Comment by DaAwesomeP** [comment]
I have added functionality for a notifications bubble in the nav.

**Comment by DaAwesomeP** [comment]
Angular seems to be updating it automatically.
