### ISSUE TITLE
Topics do not display all posts

### ISSUE THREAD

**Issue by DaAwesomeP** [wendelltron/tekapp#26]
When choosing a topic from the main page, not all of the posts show.

**Comment by jean1880** [comment]
Will look into this, see what is going on, should be fixed before it goes to beta.

**Comment by DaAwesomeP** [comment]
I'm still having this issue.

**Comment by jean1880** [comment]
Which topic thread were you browsing? I want to see what else it is doing

**Comment by DaAwesomeP** [comment]
Look at the Tek Syndicate App thread. The last post listed is #30 from 22 days ago.

**Comment by DaAwesomeP** [comment]
Let me check the object in Chrome and see what;s going on.

**Comment by jean1880** [comment]
kk, thank you, that's what I was about to do myself lol

**Comment by DaAwesomeP** [comment]
Odd. In Chrome is loads to `#40` (13 days ago). The posts object in the topic object also only lists 40 onjects.

**Comment by jean1880** [comment]
From tracking the function, for some reason, the infinite scrolling is not triggering after a few calls, and the app begins to experience bad hanging, I noticed  that the latest.json calls in the background begin to breakdown too.

**Comment by DaAwesomeP** [comment]
Oh, I was also going to mention something about the `latest.json`. They build up too quickly (nothing stops new intervals from being created) and they are too short. It think that we should have it update only when the topics page is actually viewed or the the background interval for push notifications fires. Otherwise data will be gobbled up quickly.

**Comment by jean1880** [comment]
Yes, I agree with that, I wanted to slow down the refresh time, and integrate pull down to refresh for manual fetching

**Comment by jean1880** [comment]
found the bug as well

**Comment by jean1880** [comment]
will push up fix

**Comment by jean1880** [comment]
the fix will come in with several performance fixes as well, lots of render jitters etc I have been working on

**Comment by jean1880** [comment]
Fixed and tester
