### ISSUE TITLE
Bootstrap Info Alert is purple (not blue)

### ISSUE THREAD

**Issue by DaAwesomeP** [wendelltron/tekapp#28]
The [Bootstrap Alerts](http://getbootstrap.com/components/#alerts) should be blue, not purple. This is currently observed on the settings page.

**Comment by jean1880** [comment]
Keep in mind that this app is not using the default bootstrap theme, but a custom theme,if we want to redesign the theme, we can open an issue for that, an rebuild the theme, but it is not a bug, just the nature of the theme.

**Comment by jean1880** [comment]
This is the theme I am currently using https://bootswatch.com/cyborg/

**Comment by DaAwesomeP** [comment]
Well then it's not really a bug. I thought that there could be an `rgba()` with transparency being affected by the dark background. If that's just your preference, then I don't mind. If someone on the forums rages about it, then we'll have to change it.The theme looks great, so there's no point in going through and changing little things or starting from scratch.

**Comment by jean1880** [comment]
Just was a nice theme that came close to the main forums styling, made it much easier to base off of. Down the road, if someone is feeling super adventurous, the they could be easily switched out to a custom version, just saw no need at this time
