### ISSUE TITLE
Fix small icon

### ISSUE THREAD

**Issue by DaAwesomeP** [wendelltron/tekapp#30]
Developer: The current icon has a transparent border around a smaller app icon. The icon should fill almost the entire image to be the same size as other app icons and to not look out of place.

---
 - [x] Resize/redesign icon to fill entire image (`/icon.png`)
 - [x] Resize all other app icon sizes in `res/icon` to match it

**Comment by DaAwesomeP** [comment]
@jean1880 How does this look to you?
![icon inkscape](https://cloud.githubusercontent.com/assets/4472083/7195788/6eb92afc-e48b-11e4-915d-82a2dc859ede.png)

**Comment by jean1880** [comment]
i tend to favour the cleaner, non-embossed look, following modern flat design, but I like this one too. I think we could see if we could get any feedback from the community, see if they have a preference. It's not overly hard to switch out the icons if we so choose to down the road

**Comment by DaAwesomeP** [comment]
I was mainly bugged that it was too small. Tomorrow I'll post to the forum thread about it (clean vs embossed). I think that we should keep the drop shadow on the Raze the World logo though. It makes it look pretty cool.

**Comment by jean1880** [comment]
Yeah, the size always irked me, had used an auto icon generator to quickly whip out a few icons with the effect I wanted, never got around to rebuilding them. Ultimately, if the people are happy, I am happy lol, I don't need to be Apple,and tell  them what to like :p

**Comment by DaAwesomeP** [comment]
That's the Tek Syndicate way of things!

**Comment by jean1880** [comment]
:beers:

**Comment by DaAwesomeP** [comment]
Vote at the forum - [Tek Syndicate App: Icon Style Poll (please participate by favoring an icon)](https://forum.teksyndicate.com/t/tek-syndicate-app-icon-style-poll-please-participate-by-favoring-an-icon/78681)

**Comment by DaAwesomeP** [comment]
Finished!
