### ISSUE TITLE
Right-control menu rebuild

### ISSUE THREAD

**Issue by jean1880** [wendelltron/tekapp#34]
The jazny-bootstrap push/pull menu should be rebuilt, to make use of css transforms, rather than just the transitions, with left/right moves. This will enable the devices to render the transitions using their GPUs, rather than their CPUs, it also gives the benefit of using a separate browser thread when performing a the process, giving a smoother experience to the user.

#### Success Criteria
- [ ] Menu uses transform: translate()
- [ ] Menu has less jitter

**Comment by DaAwesomeP** [comment]
We're simply going to move over to [Ionic's built-in system for this](http://ionicframework.com/docs/api/directive/ionSideMenus/) right?

**Comment by jean1880** [comment]
After experimentation, no, we won't be using ionic, it is still only using css for animations, and doing the same tricks I was already implementing for speed boosts. So, we will continue using the curent menu, and will fix  the height bug you  are having with the older device.

**Comment by DaAwesomeP** [comment]
Have you tried things other than Jasny and Ionic? There's also [this](https://github.com/iamphill/Bootstrap-Offcanvas) and [this](https://material.angularjs.org/#/demo/material.components.sidenav). The latter is Angular compatible and copies Android's Material Design.

**Comment by jean1880** [comment]
We can choose whatever menu we want, the performance won't change, we're pushing it as far as it can go. I might have an idea on how to solve it. If we close the side menu after the data is displayed, it will be much smoother, just will have to make sure we close the menu on each page. Was going to play with that today, see if it smooths out a bit. Just didn't like to do that as it makes a lot of repetitive code.

**Comment by DaAwesomeP** [comment]
We should also remove as many `$timeout`s and `$interval`s as we can. Using actual events is always way faster and uses less resources. Plus, you won;t be waiting for something to complete. This is what I did with `FormatHTML`.

**Comment by jean1880** [comment]
Yeah, by implementing it on the end of the render, it will kill the set timeout funcitonality, I agree, didn't like the way that I was doing timeouts, Thanks for the format improvement, btw, it's great.

**Comment by jean1880** [comment]
New implementation waits on data fetch before closing, giving immediate close on display, with smoother animations
