### ISSUE TITLE
Light Background and no touch

### ISSUE THREAD

**Issue by DaAwesomeP** [wendelltron/tekapp#36]
This is a new bug. I only have this problem on my phone. I do not see this in Chrome nor the Nexus 5 API 19 emulator.
![screenshot_2015-04-20-13-51-30](https://cloud.githubusercontent.com/assets/4472083/7242883/8a919b5c-e78c-11e4-81f5-c4a773edd9b8.png)
Touch and scroll events seem to be ignored. The menu button (both physical and onscreen) is also ignored. This is on an older version of Android, so I can't debug it from the Chrome debugger via USB.

**Comment by jean1880** [comment]
Which version of android is it?

**Comment by DaAwesomeP** [comment]
4.2.2. It's worked fine up until this point (the animations were skippy, but that is expected), so I don't understand what was changed that could cause this.

**Comment by jean1880** [comment]
Alright, well, probably has to do with the changes in the infinite scrolling and menu, specifically fixes for the menu. I am working on integrating the ionic framework to give native side navigation menus in the app to reduce animation jitters, so that will be resolved with that. Once that is done, we should get much better performance on a lot of those animations

**Comment by DaAwesomeP** [comment]
I'll stick to only updating the JavaScript and page layout for now then. Ionic will be a little of a learning curve for me (I've only really ever used Bootstrap), but its mostly the same concepts (danger becomes assertive, etc.). It's a much for full system though. I noticed that they even have an infinite scroll feature built it.

We should find a way to not include ionicons though. We already have Font Awesome (it matches the site) and more resources slow down the app's load time. We can probably just have Grunt omit it.

**Comment by jean1880** [comment]
It will be one step at a time transition. Fist I want to get it up with all basic functionality working, then we will make use of more of their functions. Using Ionic will fix some of the performance concerns I was getting as this became larger. For the most part though, we will still be using bootstrap etc, ionics power lies in hybrid menus and animations, plus some other nice mobile libraries built in.

**Comment by DaAwesomeP** [comment]
I really think that we should stick to one or the other in the end. The transition can use both, but for the first release we should be using one or the other. Ionic has everything that Bootstrap has. Once you submit your commit with the basic implementation I'll start working on it too.

**Comment by jean1880** [comment]
Oh, yeah, I Agree, just meant that it was going to be a gradual transition, currently I am having a hell of a time getting it to start working. Trying to bring ionic into our app with their bower package, have always done it from ionic to start.

**Comment by DaAwesomeP** [comment]
The background problem was fixed by simply adding `background-color` to the CSS, but the rendering and scrolling problems seem to be a known bug in Phonegap/Cordova with Android 4.2.2. Lesson learned - research a phone before actually buying it.
