### ISSUE TITLE
Youtube Links broken

### ISSUE THREAD

**Issue by jean1880** [wendelltron/tekapp#39]
Youtube links are not opening

**Comment by DaAwesomeP** [comment]
Links or embeds? I thought I had fixed the embeds. Links are were never implemented from our end.

**Comment by jean1880** [comment]
Ive finally figured out the problem, it has to do with the way the lazyYT handles the youtube objects. It is wanting to bind an event to the object, but since the object is not actually in the dom, it binds it to an object that gets lost, just rewriting it so that it embeds the event inline, and targets the text title properly. Unless you have a cleaner solution

**Comment by jean1880** [comment]
NVM, thought of a better solution
