### ISSUE TITLE
Category list not functioning

### ISSUE THREAD

**Issue by jean1880** [wendelltron/tekapp#41]
The category dropdown list is not functioning

**Comment by DaAwesomeP** [comment]
It seems that you have to click the very top of it. Then the list is underneath the topic list. I can see this in web inspector.

**Comment by DaAwesomeP** [comment]
We might as well fix this by putting it into the navbar as we are going to anyways. A simple `ng-repeat` should do it. Then we will have it clear/reload the extra list in the navbar on view change.

**Comment by DaAwesomeP** [comment]
A similar problem has happened with the profile link problem in posts headers. You can only click the top part.

**Comment by DaAwesomeP** [comment]
Fixed
