### ISSUE TITLE
Crosswalk bugs

### ISSUE THREAD

**Issue by DaAwesomeP** [wendelltron/tekapp#43]
Bugs to fix:
 - [x] Menu button event never fires (physical menu button doesn't work)
 - [x] Categories list in home page nav menu is now cut off

**Comment by DaAwesomeP** [comment]
I have submitted a bug: [menubutton event doesn't work](https://crosswalk-project.org/jira/browse/XWALK-4004).

**Comment by DaAwesomeP** [comment]
The categories list bug is only apparent on smaller screens. I assume that this is from Jasny Boostrap's method to pull down the menu instead of slide.

**Comment by DaAwesomeP** [comment]
@jean1880 do you have any problems with the menu button or your devices or emulators? This is a pretty big bug.

**Comment by jean1880** [comment]
I have been digging around,tying to find out if anyone else has been having this issue, with no success. I have confirmed it on the emulator, however I do not own a device that has a menu button. I am wondering if we are having an issue of cordova not initializing properly. In the latest build the back button is now no longer working either.

**Comment by jean1880** [comment]
https://issues.apache.org/jira/browse/CB-8921 Tested in basic app, and replicated in flat cordova 5.0, seems it may be an issue with cordova itself.

**Comment by jean1880** [comment]
I'm actually going through and fixing cordova for this, in the debugging process it looks like something has broken in cordova and it is no longer listening to those button the way it is supposed to be. Once i get it fixed, will make pull request to cordova, and provide the patch file to us in the mean time

**Comment by jean1880** [comment]
Alright, I have a temporary fix pushed up, we will have to manually add this file in our platforms to fix, destination is 
```
platforms/android/CordovaLib/src/org/apache/cordova

**Comment by DaAwesomeP** [comment]
@jean1880 You should post your actual fix (code) to the Cordova JIRA to hurry along the fix.
