### ISSUE TITLE
Local storage is not saved after app close

### ISSUE THREAD

**Issue by DaAwesomeP** [wendelltron/tekapp#45]
While the app is open, the Local Storage is manipulated and stored correctly. However, when the app is closed and reopened, it resets to an earlier local storage. I have triple checked the code that checks the local storage at the start with `console.log()` and it is not replacing it at startup. Either Cordova or Crosswalk is causing the problem. I do not experience this in Chrome.

---
 - [ ] Make local storage save between app sessions

**Comment by jean1880** [comment]
Will check it out, it definitely was saving before

**Comment by DaAwesomeP** [comment]
Ultimately we should disable all of the settings for the beta release since they don't actually do anything. It should be fixed first though.

**Comment by jean1880** [comment]
Yeah, that's fine, we can comment out the links to the settings, but we need local storage for caching as well. just booting up the app in the debugger to figure out what is happening

**Comment by jean1880** [comment]
Cordova 5.0 and crosswalk seemed like an awesome idea, did not expect it to be so glitchy, it's pretty bad

**Comment by DaAwesomeP** [comment]
Good thing that this is a beta! :relieved:

**Comment by jean1880** [comment]
lol, yes, that's true, was surprised when I was testing cordova scripts that no one had bothered to test it, their update had made it so that absolutely no button events would fire, except back. *face palm*

**Comment by jean1880** [comment]
I'm unable to replicate this bug, local storage for cached topics is definitely functional, where specifically is it occurring?

**Comment by DaAwesomeP** [comment]
Set any option to something that it isn't on the settings page. Close the app and reopen it. You settings will not be saved. They are saved in Chrome but not on my device nor emulator. I did a remote inspect from the Chrome debugger and found that the app is correctly updating the local storage, but Cordova doesn't keep that change after a total app reload (closing it from multitasking).

We do have a service that checks at the app start if the local storage or keys in it are missing, but I checked it extensively with `console.log()` and it's not firing at all (it is not resetting it).

The topics are harder to see if they are cached without the inspector because the first few are always the same and it fetches them when you launch the app.

**Comment by jean1880** [comment]
I did diff check to see what was changing in topics,and closed the app completely, as well as did reinstall to start with fresh local storage, and turned data right off to make sure that nothing was being pulled in at app start, will dig through the settings to figure out what is going on there, has to be our scripts somewhere

**Comment by DaAwesomeP** [comment]
So you were you able to replicate the bug?

**Comment by jean1880** [comment]
yes, I was, going through now to figure out what is happening, it only effects settings

**Comment by jean1880** [comment]
Problem is intermittent, haven't figured out why it works sometimes, and others not. It is however not actually saving in the root file structure, so it doesn't look like it is our scripts. will debug crosswalk, and see why it is failing to save in the local file

**Comment by jean1880** [comment]
Issue is in crosswalk core engine, cannot debug, writing file interface to handle our own cached data in the device, will be stored in app's data cache folder, which allows user to clear the cache if they choose to reset the data. Implemented with [Cordova File Plugin](http://plugins.cordova.io/#/package/org.apache.cordova.file), will create service to interface with the files

**Comment by jean1880** [comment]
Looks like ngCordova has functionality built in through [$cordovaFile](http://ngcordova.com/docs/plugins/file/)  will implement through that

**Comment by DaAwesomeP** [comment]
Will be be compatible with Chrome? That is the easiest way to test basic things and I think that we should leave it compatible. We should use an if staement to choose the right storage method:
```javascript
if (!!window.cordova) {
  PhoneGap.init(function () {
      // Is Cordova - Use $cordovaFile method
  });
}
else {
  // Is not Cordova - Use old method
  localStorageService.set('user', JSON.stringify(userStorage.user));
}
```

**Comment by jean1880** [comment]
is there a use case where this isn't going to be an app?

**Comment by jean1880** [comment]
I can add the catch, I get the ease of testing in browser, I just never test in browser.
