### ISSUE TITLE
Sort Posts by time

### ISSUE THREAD

**Issue by jean1880** [wendelltron/tekapp#46]
Currently posts are added to the post stream as they arrive, we should add a sort to the ng-repeat to filter by last post time, that way if posts load out of order, they correct themselves as they arrive

---
 - [ ] Order posts by time and pin

**Comment by DaAwesomeP** [comment]
`orderBy` can be used with `ngRepeat` in the HTML template: https://docs.angularjs.org/api/ng/filter/orderBy

**Comment by jean1880** [comment]
I know, i'll be adding it later tonight

**Comment by DaAwesomeP** [comment]
I'll add a moment Unix time santization method.

**Comment by DaAwesomeP** [comment]
@jean1880  Be sure to keep the pinned ones that are usually at the top at the top. I'm sure the stickied ones have another JSON key to them.
