### ISSUE TITLE
Update Navbar

### ISSUE THREAD

**Issue by jean1880** [wendelltron/tekapp#7]
#### User Story
As a developer, I need the nav bar to be more modular, allowing changes on one menu set, to change on both the mobile, and tablet nav views

====
#### Success Criteria
- [x] Break navbar out of main index.html file
- [x] Break menu options into separate templates
- [x] Have navbar render, in similar fashion, for both small mobile display, as well as for tablets
- [x] Make use of built-in Android options button

**Comment by jean1880** [comment]
Look into integrating https://jasny.github.io/bootstrap/examples/navmenu-push/ into the app, combined with my original concept

**Comment by DaAwesomeP** [comment]
I think we're going to need that for all of the dropdowns. I just tested the app in the default Nexus 5 emulator (very high resolution screen), and the categories dropdown doesn't quite fit on screen. We can make a function that accepts JSON objects and opens a slider. That will make it easy to integrate into everything.

With the current dropdowns, I have noticed that opening one doesn't close the others. They can stack up on each other.

**Comment by jean1880** [comment]
yeah, the nav is currently undergoing a complete rewrite, using swipe libraries, and pull in menus, which will fix all of these issues, plus allow for back navigation, and eliminate the need for bottom bars for adding topics, adding posts, etc.

**Comment by jean1880** [comment]
Also plan on making it contextual, so, the menu changes based on where you are, aka, main page, ability to create topics,in a topic, add a post, etc

**Comment by jean1880** [comment]
Bug on topic search needs to be fixed
