### ISSUE TITLE
Add Settings Page

### ISSUE THREAD

**Issue by jean1880** [wendelltron/tekapp#9]
#### User Story
As a user, I would like to control various functionality of the app, to limit app to wifi access only, or turn push notifications on or off

===
#### Success Criteria
- [x] Add setting page to "#other" nav menu
- [x] Create route, controller, and view for settings page
- [x] Allow user to turn push notifications off/on (does not control anything, but option available)
- [x] Allow user to set app to use wifi only (does not control anything, but option available)
- [x] Create a settings API
- [x] Create a general way to load the settings onto the page (*broken*)
- [x] Make setting persistent (do not reload/rewrite them from a file on reload).

**Comment by DaAwesomeP** [comment]
Ideally, we would have a JSON data file like this:
```json
{
  "wifiOnly": {
    "name": "Wifi Only",
    "type": "onoff",
    "default": false
  },
  "pushFreq": {
    "name": "Push Update Frequency",
    "type": "select",
    "select": {
      "15": "15 minutes",
      "30": "30 minutes",
      "60": "1 hour",
      "120": "2 hours",
      "180": "3 hours",
      "0": "Manual"
    },
    "default": "60"
  }
  },
}
```
The settings page would then create an object based on those settings that is perstsent and globally available:
```json
{
  "wifiOnly": true,
  "pushFreq": "60"
}
```
This object would be filled at first run with the default values and add new default values on app update. This system allows for all settings to be created/viewed with a template, accessible by all pages, and easily debugged.

**Comment by jean1880** [comment]
Yes, I agree, we can store the file in a JSON storage folder, in the app, for parsing at run time.

**Comment by DaAwesomeP** [comment]
There is now settings page that loads the settings dynamically from a JSON file. Settings are stored in `$user.prefs`. It is half-functional. I need to solve this problem: https://groups.google.com/forum/#!topic/angular/KAr02kNSJPs

**Comment by DaAwesomeP** [comment]
The settings page and configuration JSON file for it is now functional. However, settings are not persistent. @jean1880 do we have a universal API to store data in localStorage? We should replace `User.js` and `$user` with a more permanent system.

**Comment by jean1880** [comment]
persistence is accessed  using the $localstorage service, but we should only use that for maintaining persistence, while keeping a local active copy will reduce rad time. When it is stored  in localstorage, it has to be stored as a string, then parsed  back out as JSON.

**Comment by DaAwesomeP** [comment]
I see. We can keep a local copy (as there is a local object now) for reading, and we can create a function that updates it when `$localstorage` is written to. I'll work on it. We'll then have a full API for accessing, viewing, creating, and changing settings.

**Comment by jean1880** [comment]
Yeah, that was my end plan with it, sounds good

**Comment by DaAwesomeP** [comment]
- Persistence has been added
  - `FactoryUserStorage` contains the currently cached user object (replaces `$user`) and can be accessed with `FactoryUserStorage.user`. This value can be updated and then saved (see next bullet).
  - `FactoryUserStorage` contains a function to save the current user object to localStorage and can be accessed with `FactoryUserStorage.save()`.
 - The settings page now saves and loads the persistent settings
 - Other pages before using `$user` have been updated to include `FactoryUserStorage`, change `FactoryUserStorage.user` instead of `$user`, and save their changes.
